### ISSUE TITLE
why kotlin and not java? :D +1 more plugin on server (KotlinLib)

### ISSUE THREAD

**Issue by ghost** [Creeperface01/BowHitAlert#1]

**Comment by Creeperface01** [comment]
For you 1 more plugin = 1 more minute to download it
For developer -> more saved time during development and better features

**Comment by ghost** [comment]
exemples pls?

**Comment by ghost** [comment]
of "features" ?

**Comment by Creeperface01** [comment]
https://kotlinlang.org/docs/reference/ read it
